# Generated by Django 6.0.3 on 2026-03-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_seller_customuser_is_seller_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
