# Generated by Django 6.0.3 on 2026-03-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Commission', max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage fee on final sale price.', max_digits=5)),
                ('flat_fee', models.DecimalField(decimal_places=2, default=0, help_text='Flat fee per transaction.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='fraud_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
