# Generated by Django 6.0.3 on 2026-03-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_item_current_price_bid_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='received_by_buyer',
            field=models.BooleanField(default=False),
        ),
    ]
